/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://gvqvhk4o3vhg7hcqday736zb3q.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-sb6iaojtpfgvxli6lmo3hptm7m",
    "aws_cognito_identity_pool_id": "us-east-1:f7d1c243-8d19-480f-a2eb-d79f479f072d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_2RGSgp7ew",
    "aws_user_pools_web_client_id": "3a8cs220iguhv1ghqvg38m94j9",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "kafkaboostwebsitef5b2ed53e119465ebb1961d042ec48af3c1-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
